<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Bootstrap CSS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- jQuery -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="styles.css">
    <title>Document</title>
</head>
<body>


    <!-- Button trigger modal for LOGIN -->
    <button type="button" class="btn btn-primary    " data-bs-toggle="modal" data-bs-target="#exampleModal">
        Launch demo modal
    </button>

     <!--Modal for LOGIN-->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="myform">
                        <h1 class="text-center">Login Form</h1>
                        <form>
                            <div clas="mb-3 mt-4">
                                <label for="Emailinput" class="form-label">Email Address</label>
                                <input type="email" class="form-control" id="Emailinput" aria-describedby="emailHelp">
                            </div>
                            <div class="mb-3">
                                <label for="Passwordinput" class="form-label">Password</label>
                                <input type="password" class="form-control" id="Passwordinput" aria-describedby="passwordHelp">
                            </div>
                            <button type="submit" class="btn btn-light mt-3">LOGIN</button>
                            <p>Don't have an Account?<a href="../Signup/index.php"><button type="button" class="btn btn-dark">Sign-Up</button></a></p>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
<?php
